-- Query 1

-- Users Table
CREATE TABLE users (
    id TEXT PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    username TEXT NOT NULL,
    first_name TEXT,
    last_name TEXT,
    image_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Calls Table
CREATE TABLE calls (
    id TEXT PRIMARY KEY,
    created_by_id TEXT NOT NULL REFERENCES users(id),
    state JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    started_at TIMESTAMP WITH TIME ZONE
);

-- Participants Table
CREATE TABLE participants (
    id SERIAL PRIMARY KEY,
    call_id TEXT NOT NULL REFERENCES calls(id),
    user_id TEXT NOT NULL REFERENCES users(id),
    joined_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    left_at TIMESTAMP WITH TIME ZONE,
    UNIQUE(call_id, user_id)
);

-- Recordings Table
CREATE TABLE recordings (
    id TEXT PRIMARY KEY,
    call_id TEXT NOT NULL REFERENCES calls(id),
    filename TEXT NOT NULL,
    start_time TIMESTAMP WITH TIME ZONE,
    end_time TIMESTAMP WITH TIME ZONE,
    url TEXT NOT NULL
);

-- Polls Table
CREATE TABLE polls (
    id SERIAL PRIMARY KEY,
    call_id TEXT NOT NULL REFERENCES calls(id),
    question TEXT NOT NULL,
    options JSONB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Poll Votes Table
CREATE TABLE poll_votes (
    id SERIAL PRIMARY KEY,
    poll_id INTEGER NOT NULL REFERENCES polls(id),
    user_id TEXT NOT NULL REFERENCES users(id),
    option_index INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(poll_id, user_id)
);

-- Superchats Table
CREATE TABLE superchats (
    id SERIAL PRIMARY KEY,
    call_id TEXT NOT NULL REFERENCES calls(id),
    user_id TEXT NOT NULL REFERENCES users(id),
    message TEXT NOT NULL,
    amount NUMERIC(10, 2) NOT NULL,
    payment_status TEXT NOT NULL DEFAULT 'pending',
    order_reference TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Query 2
-- Chat Messages Table
CREATE TABLE chat_messages (
    id SERIAL PRIMARY KEY,
    call_id TEXT NOT NULL REFERENCES calls(id),
    user_id TEXT NOT NULL REFERENCES users(id),
    message TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Query 3
-- Rename the 'message' column to 'text'
ALTER TABLE chat_messages
RENAME COLUMN message TO text;

-- Drop the old user_id column and its foreign key constraint
ALTER TABLE chat_messages
DROP COLUMN user_id;

-- Add the new 'sender' column that the code is using
ALTER TABLE chat_messages
ADD COLUMN sender TEXT;

-- Query 4
-- Drop the existing, incorrect tables first to avoid conflicts
DROP TABLE IF EXISTS "public"."poll_votes";
DROP TABLE IF EXISTS "public"."poll_options";
DROP TABLE IF EXISTS "public"."polls";
DROP TABLE IF EXISTS "public"."chat_messages";

-- Recreate the Polls table with all required columns
CREATE TABLE "public"."polls" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "call_id" text,
    "question" text,
    "is_active" boolean DEFAULT true,
    "duration_seconds" integer
);
ALTER TABLE "public"."polls" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."polls_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
ALTER TABLE ONLY "public"."polls" ADD CONSTRAINT "polls_pkey" PRIMARY KEY (id);


-- Create the Poll Options table
CREATE TABLE "public"."poll_options" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "poll_id" bigint,
    "text" text,
    "position" smallint
);
ALTER TABLE "public"."poll_options" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."poll_options_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
ALTER TABLE ONLY "public"."poll_options" ADD CONSTRAINT "poll_options_pkey" PRIMARY KEY (id);
ALTER TABLE ONLY "public"."poll_options" ADD CONSTRAINT "poll_options_poll_id_fkey" FOREIGN KEY (poll_id) REFERENCES public.polls(id) ON DELETE CASCADE;


-- Create the Poll Votes table
CREATE TABLE "public"."poll_votes" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "user_id" text,
    "poll_option_id" bigint
);
ALTER TABLE "public"."poll_votes" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."poll_votes_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
ALTER TABLE ONLY "public"."poll_votes" ADD CONSTRAINT "poll_votes_pkey" PRIMARY KEY (id);
ALTER TABLE ONLY "public"."poll_votes" ADD CONSTRAINT "poll_votes_poll_option_id_fkey" FOREIGN KEY (poll_option_id) REFERENCES public.poll_options(id) ON DELETE CASCADE;


-- Recreate the Chat Messages table with the correct columns
CREATE TABLE "public"."chat_messages" (
    "id" bigint NOT NULL,
    "call_id" text,
    "sender" text,
    "text" text,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL
);
ALTER TABLE "public"."chat_messages" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."messages_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
ALTER TABLE ONLY "public"."chat_messages" ADD CONSTRAINT "messages_pkey" PRIMARY KEY (id);

-- IMPORTANT: Enable Realtime on the new tables
-- You might need to do this in the Supabase UI under Database > Replication,
-- but this command attempts to do it via SQL.
alter publication supabase_realtime add table polls, poll_options, poll_votes, chat_messages;


-- Query 5
ALTER TABLE polls
ADD COLUMN end_time TIMESTAMP WITH TIME ZONE;

-- Query 6
-- Add the poll_id column to the poll_votes table
ALTER TABLE "public"."poll_votes"
ADD COLUMN "poll_id" bigint;

-- Add a foreign key to ensure data integrity
ALTER TABLE "public"."poll_votes"
ADD CONSTRAINT "poll_votes_poll_id_fkey"
FOREIGN KEY ("poll_id")
REFERENCES "public"."polls"(id)
ON DELETE CASCADE;

-- Query 7: Fix superchats table schema (Revised)
-- Rename user_id to sender_id to match the application code
ALTER TABLE "public"."superchats" RENAME COLUMN "user_id" TO "sender_id";

-- Add sender_name column to store the name of the user sending the superchat
ALTER TABLE "public"."superchats" ADD COLUMN "sender_name" TEXT;

-- Add currency column
ALTER TABLE "public"."superchats" ADD COLUMN "currency" TEXT;

-- Add is_pinned column for the pinning feature
ALTER TABLE "public"."superchats" ADD COLUMN "is_pinned" BOOLEAN DEFAULT false;

-- Rename created_at to timestamp to match the application code
ALTER TABLE "public"."superchats" RENAME COLUMN "created_at" TO "timestamp";

-- Note: The 'payment_status' column is intentionally kept for webhook functionality.

